### PR TITLE
Bringing in Rory's Ass1 + Image Location Changes

### PR DESCRIPTION
**Pull request by RoryIAngus**
I have reconfigured how the images are stored, so they are in their own folder to prevent issues from arising. DataFutures/USERNAME.
I updated the location of the images that I moved. This was tested
My chapter is almost completed.
Git Ignore updated as well to help with managing the code base. _book folder still not working correctly. Need help to prevent it being uploaded.

### CODE REVIEW

**Comment by RoryIAngus** [comment]
I don't think I had the changes in the gitignore file in my master branch so it didn't end up here.
So I am going to close this as I can't get it to pull again from my repo.
Will try agian

**Comment by D-r-K** [comment]
Rory, you are still comitting HTML and json in this request. Corinna also had some challenges with this. Perhaps check in with her to see how she overcame the problem.

**Comment by RoryIAngus** [comment]
I think it was part of the original fork that I did. The gitignore file should deal with it. 
I will keep working on it

**Comment by RoryIAngus** [comment]
RIGHT!!!
This is now matching all the files that I am pushing to you. Other than the new one of course that is the gitignore file that will save anyone else from this pain.

**Comment by RoryIAngus** [comment]
I have deleted the _book directory and its contents from my github repo. This should fix the files you are seeing Detlev

**Comment by RoryIAngus** [comment]
I can now confirm that after building the book in RStudio and it creating the _book folder and all its contents it has not picked up that change to merge back to the repo. As far as it is concerned it never happened.

**Comment by perrystephenson** [comment]
All good - nice work team

**Pull request merged**
